
// Define const for action reducer
const ADD_ITEM = 'ADD_ITEM'
const DELETE_ITEM = 'DELETE_ITEM'
const TOGGLE_ITEM = 'TOGLE_COMPLETE'
const CLEAR_ITEMS = 'CLEAR_ITEMS'
const AlERT_MESSAGE = 'AlERT_MESSAGE'
const TOGGLE_MODAL = 'TOGGLE_MODAL'

export  {ADD_ITEM,DELETE_ITEM,TOGGLE_ITEM ,CLEAR_ITEMS,AlERT_MESSAGE,TOGGLE_MODAL
}
